---
- name: Install Azure DevOps Agent and Docker on EC2 Instance
  hosts: azure_pipeline_agent
  become: true
  vars:
    azure_devops_pat: "{{ lookup('env', 'AZURE_DEVOPS_PAT') }}"  # Set via environment variable or extra vars

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - jq
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install Docker
      apt:
        update_cache: yes
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add 'ubuntu' user to the Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create agent directory
      file:
        path: /home/ubuntu/myagent
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Download Azure DevOps agent
      get_url:
        url: "https://vstsagentpackage.azureedge.net/agent/3.246.0/vsts-agent-linux-x64-3.246.0.tar.gz"
        dest: /home/ubuntu/myagent/vsts-agent-linux-x64-3.246.0.tar.gz
        owner: ubuntu
        group: ubuntu

    - name: Extract agent package
      ansible.builtin.unarchive:
        src: /home/ubuntu/myagent/vsts-agent-linux-x64-3.246.0.tar.gz
        dest: /home/ubuntu/myagent
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Configure the Azure DevOps agent
      command: ./config.sh --unattended --url https://dev.azure.com/mirzadismail --auth pat --token "{{ azure_devops_pat }}" --pool Docker-App --agent AzurePipelineAgent-EC2
      args:
        chdir: /home/ubuntu/myagent
      become: false  # Run without sudo to avoid permission issues

    - name: Install agent as a service
      command: ./svc.sh install
      args:
        chdir: /home/ubuntu/myagent

    - name: Start the agent service
      command: ./svc.sh start
      args:
        chdir: /home/ubuntu/myagent

